#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias ox='open -a Xcode ./'
alias ddd='rm -rf ~/Library/Developer/Xcode/DerivedData/*'
alias rp='rm -rf Pods/;bundle exec pod install'
alias pall='gia ./; gcf; gpF'
alias kxc='ddd; rp; ox'
